/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as AuthenticatedWebAdminRouteImport } from './routes/_authenticated.web-admin'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated.manager'
import { Route as AuthenticatedHospitalAdminRouteImport } from './routes/_authenticated.hospital-admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWebAdminRoute = AuthenticatedWebAdminRouteImport.update({
  id: '/web-admin',
  path: '/web-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHospitalAdminRoute =
  AuthenticatedHospitalAdminRouteImport.update({
    id: '/hospital-admin',
    path: '/hospital-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hospital-admin': typeof AuthenticatedHospitalAdminRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/web-admin': typeof AuthenticatedWebAdminRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hospital-admin': typeof AuthenticatedHospitalAdminRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/web-admin': typeof AuthenticatedWebAdminRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/hospital-admin': typeof AuthenticatedHospitalAdminRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/_authenticated/web-admin': typeof AuthenticatedWebAdminRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/hospital-admin'
    | '/manager'
    | '/web-admin'
    | '/api/ai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/hospital-admin' | '/manager' | '/web-admin' | '/api/ai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/hospital-admin'
    | '/_authenticated/manager'
    | '/_authenticated/web-admin'
    | '/api/ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAiRoute: typeof ApiAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/web-admin': {
      id: '/_authenticated/web-admin'
      path: '/web-admin'
      fullPath: '/web-admin'
      preLoaderRoute: typeof AuthenticatedWebAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hospital-admin': {
      id: '/_authenticated/hospital-admin'
      path: '/hospital-admin'
      fullPath: '/hospital-admin'
      preLoaderRoute: typeof AuthenticatedHospitalAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHospitalAdminRoute: typeof AuthenticatedHospitalAdminRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedWebAdminRoute: typeof AuthenticatedWebAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHospitalAdminRoute: AuthenticatedHospitalAdminRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedWebAdminRoute: AuthenticatedWebAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAiRoute: ApiAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
